### ISSUE TITLE
Trend dello sviluppatore 2024

### ISSUE THREAD

**Issue by riccardogenova** [riccardogenova/Il-manuale-del-rookie-dev#113]
Sviluppare una sezione che racconti quali sono le tecnologie che hanno un trend di crescita e che potrebbe essere interessante apprendere per il 2024.

**Comment by LotherDin** [comment]
Interessante, potremmo associare ai trend anche le competenze richieste per vedere come cresce un trend, rispetto al mercato attuale, nazionale/internazionale.

**Comment by riccardogenova** [comment]
Duplicato di https://github.com/riccardogenova/Il-manuale-del-rookie-dev/issues/118
